### ISSUE TITLE
the anchor option "middle" not work and throw Error

### ISSUE THREAD

**Issue by yuicer** [vega/vega-label#21]
```js
VM7167:1 Uncaught TypeError: Cannot read property 'getRange' of undefined
    at eval (eval at test (placeMarkLabel.js)
    at test (placeMarkLabel.js)
```

the option anchor is ["middle", "right", "left"]

Did this is a bug or ??

**Comment by chanwutk** [comment]
Can you share the vega spec that give you the error?

**Comment by yuicer** [comment]
@chanwutk  here the test spec

https://vega.github.io/editor/#/url/vega/N4Ig7glgJgLgFiAXAVgAyoDQjgUwgczhiQGZ0sAjAQwGMBrfAJwHsBXAOyiRAGIr+QWKFRhUkAbVDsqAWxzcAygEEAcgGkAogE0A+ioDyAEQ0LBIAG5UANqxwBnCaDo4AntwDCcCADModqr7+0mZQOAAO8EiY4HiExCjkIC6opOjRLgCMpGjpNKQATGgAvhhOrtwAUlRhVOwh4ZGIGVhgsURIGWlYyVHdWU1dSXkJqCVlboggGuz4VrVcQg0IiNGtBO2IACyJPSt9SNu5SPnoYyDOEyAAqsr1Ecv5LW3xAGw7KXtJ-W9HiGSjpXO5UmADFGLUaPJFvdSE91q93r0vkgft1hv8zhduABZZgsGg0Zh3RqPGLwpAAdkRfxO6X6JAAnDt0chigBdIpsrAyKiMOgORCSEAwFxheSTJhsMJmHDsQmhJCgVhhYQwcWgAAeios1lsURKSW1lhs4oB4GgjVAdgI0is3EgsAQBtw5MQVpt1m4LriICKfu5vP5jmFovFIEYOBoxCw3hYMm1qrEk2U6m0eiMJl9WFl8vVIFlasY2odlpAdho1jDEE4OC1lHmHQNWrdZYrVirNbrIG8EBwVi4k1CMINEytbbDxr1Md7-e4PRH+W15cr3EnUO7M4HyP9IGVqrzPasdpb1vwtu4AHIKHN6BffX6ziKxdw1Rro924wmREmQCnNLoDGMUwDWrQtaBgCBzHFbxrDsHBszlZgFRbAscCLFtvGYdgYAUCAAC88zXY4zWsG0jV1MNIWwtCsxAag4KsatCIo7gKGYGAYGYeMdz3EQ81feIhVPc9BxEVgZHEC8LgvNlfS5EBmzHFdJmrUIux7PstyHSJ604KIADpkBHJdx1XFjp00uc8gNQ9j3dM9PUmC8wC8NU7wfLAYHBdg7Ewxh40FUAnzDOYKD7MxmG8bw4ME-J5IjKMJEwTB7JE81HSzVLHOwZ45KwKhzGYaAAAloFCOpEC82x8rlOA8QkEAZDK9szEYcksHbbxiHkmooCgat8H1DlhqwZd2wFIVpDkbhVNrMxgtYhshC4qhqy-URFFUf90yAswNNnQcllo7z8DDEsECwXr+pmABJdh2BolZ9PyM4poncyQ2fSZGIe3kzHYCBISQKr4JAAiWGBxhqpAKAVrWltE021MAIzUwLIO7csBOsNvXaTkiiAA

**Comment by yuicer** [comment]
the only problem is the anchor ['middle'] option

I debug the label-transfrom. the code  in bitmap returns [bitmap, undefined], so i try to set bm1 = bm1 || bm0, and still get  error

 it seems like cannot get the correct range when it's  middle [0x5] , or the code process has some problems?

**Comment by chanwutk** [comment]
`'middle'` should not be used if you are not placing labels insider its base mark.
Can you try using `avoidBaseMark`?
```
          "transform": [
            {
              "type": "label",
              "offset": [2],
              "rect": [0, 0, {"signal": "width"}, {"signal": "height"}],
              "avoidHidden": true,
              "avoidBaseMark": false,
              "anchor": ["middle", "right", "left"],
              "padding": 0
            }
          ]
```

**Comment by yuicer** [comment]
still get the same error.....  the bm1 param here is undefined
```js
 Uncaught TypeError: Cannot read property 'getRange' of undefined
    at eval (eval at test (placeMarkLabel.js)
    at test (placeMarkLabel.js)
```

by the way , what the [ insdide its base mark] mean? its the root mark whick contains the text mark here?

**Comment by chanwutk** [comment]
`bm1` can be undefined if you only do label-to-label overlapping.
base mark means the marks that text marks refer to for positioning. In your case, you don't have it.
Could you pull your master branch again and see if it work?
Also, this repository is no longer maintained. Please see [here](https://github.com/vega/vega/tree/master/packages/vega-label) the the most updated version.

**Comment by yuicer** [comment]
thx, I'll try later~

**Comment by yuicer** [comment]
I pull the vega master branch and import vega-label to vega/index and build the vega.js
![image](https://user-images.githubusercontent.com/23371475/86429584-984de180-bd22-11ea-8690-da788fdeed38.png)

but..... still get the same error....
I'm sure there has some problems with the [middle] option......... orz     
***I'll provide the repo if needed***


![image](https://user-images.githubusercontent.com/23371475/86429611-abf94800-bd22-11ea-9aca-cabbb89dee37.png)
![image](https://user-images.githubusercontent.com/23371475/86429627-b74c7380-bd22-11ea-8e48-2a2bc5c82f51.png)
![image](https://user-images.githubusercontent.com/23371475/86429645-c0d5db80-bd22-11ea-8f9a-58b143231d71.png)

**Comment by yuicer** [comment]
demo here

https://github.com/yuicer/vega-label-transform-demo

**Comment by chanwutk** [comment]
I made a change to your demo repository to address the issue.
Please let me know if that change solve the problem.

**Comment by yuicer** [comment]
@chanwutk  It did works ~ thanks a lot

**Comment by chanwutk** [comment]
Awesome!!!
