### ISSUE TITLE
How to use in vega?

### ISSUE THREAD

**Issue by skokenes** [vega/vega-label#7]
Is this incorporated into the vega-js release yet? If so, which version? If not, any idea on a target release date?

**Comment by g3o2** [comment]
so this will be vega only? or is an interface planned for vega-lite?

**Comment by chanwutk** [comment]
Labeling will be supported in Vege-Lite too.

**Comment by g3o2** [comment]
wow!

**Comment by domoritz** [comment]
We are actively working on integrating this into Vega and Vega-Lite. Stay tuned.

**Comment by nicola** [comment]
Any progress on this?

**Comment by domoritz** [comment]
Yes, we merged it into the Vega repo and plan to include it in the build soon.

**Comment by nicola** [comment]
That's awesome! Will this also be available in vega-lite or not for now?

**Comment by domoritz** [comment]
Eventually. We only have so much bandwidth so if you want it earlier, please come help us.
